Repository micropython/micropython, pull requests merged in 2022-05, with the labels that each got.

#8612 py/compile: Only implicitly close over variables in function-like scope.
  py/emitcommon.c
  py/scope.h
  tests/basics/scope_class.py
Labels: py-core

#8617 tests/extmod: Increase timing on uasyncio tests to make more reliable.
  tests/extmod/uasyncio_basic.py
  tests/extmod/uasyncio_basic.py.exp
  tests/extmod/uasyncio_gather.py
  tests/extmod/uasyncio_heaplock.py
  tests/extmod/uasyncio_wait_task.py
  tests/extmod/uasyncio_wait_task.py.exp
Labels: tests

#8638 tools/autobuild: Update for ports/renesas-ra.
  tools/autobuild/autobuild.sh
  tools/autobuild/build-boards.sh
Labels: tools

#8548 py/parse: Allow all constant objects to be used in "X = const(o)".
  docs/reference/constrained.rst
  py/parse.c
  tests/micropython/const_alltypes.py
  tests/micropython/const_alltypes.py.exp
Labels: py-core

#8695 py/asmthumb: Provide implementations of clz/ctz for MSC.
  py/asmthumb.c
Labels: py-core
